// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA_rwP_aU5n0WiKGz-hZ1EJ5aYZPTvrUc',
    appId: '1:768852341385:web:ad846e0985826e8ff28c58',
    messagingSenderId: '768852341385',
    projectId: 'trustmap-d9d6a',
    authDomain: 'trustmap-d9d6a.firebaseapp.com',
    storageBucket: 'trustmap-d9d6a.firebasestorage.app',
    measurementId: 'G-BW90FKJCPF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPdyVIok7Jxdv9zDdQ_6SoFVzV2v299Yg',
    appId: '1:768852341385:android:3e3cb1ddceee0147f28c58',
    messagingSenderId: '768852341385',
    projectId: 'trustmap-d9d6a',
    storageBucket: 'trustmap-d9d6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3cYxtheaxCFBLMzn3MvFYVEbOeYjYl74',
    appId: '1:768852341385:ios:90eba54408abc59af28c58',
    messagingSenderId: '768852341385',
    projectId: 'trustmap-d9d6a',
    storageBucket: 'trustmap-d9d6a.firebasestorage.app',
    iosBundleId: 'com.example.safetyApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3cYxtheaxCFBLMzn3MvFYVEbOeYjYl74',
    appId: '1:768852341385:ios:90eba54408abc59af28c58',
    messagingSenderId: '768852341385',
    projectId: 'trustmap-d9d6a',
    storageBucket: 'trustmap-d9d6a.firebasestorage.app',
    iosBundleId: 'com.example.safetyApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA_rwP_aU5n0WiKGz-hZ1EJ5aYZPTvrUc',
    appId: '1:768852341385:web:e801425cf83c8145f28c58',
    messagingSenderId: '768852341385',
    projectId: 'trustmap-d9d6a',
    authDomain: 'trustmap-d9d6a.firebaseapp.com',
    storageBucket: 'trustmap-d9d6a.firebasestorage.app',
    measurementId: 'G-LE22WR105V',
  );
}
